---
title: "child_marriage"
author: "Ambalika"
date: "2023-03-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Packages used

```{r package}

library(readr)
library(tidyverse)
library(ggplot2)
library(sf)
library(rnaturalearthdata)
library(rnaturalearth)
library(colorspace)
library(themes360info)

```

## Read data

```{r data}

w_18 <- read_csv("data/child_marriage/w_18.csv")

w_18 <- w_18 %>% 
  select(geoAreaCode, geoAreaName, parentCode, parentName, ISO3, latest_value)

law_2 <- read_csv("data/child_marriage/law_2.csv")

cmf <- law_2 %>% 
  left_join(w_18, by = c("Code" = "ISO3"))

countries <- ne_countries(returnclass = "sf", scale = "medium")

cmf1 <- countries %>% 
  select(iso_a3) %>% 
  left_join(cmf, by = c("iso_a3" = "Code")) %>% 
  drop_na(Law)

cmf1 %>%
  mutate(
    LawStr = case_when(
      Law == 0 ~ "Prohibited",
      Law == 0.25 ~ "Prohibited with legal exceptions",
      Law == 0.5 ~  "Prohibited with legal exceptions for girls",
      Law == 0.75 ~ "Allowed",
      Law == 1 ~ "Allowed for girls")) ->
  cmf1


```


## Plot 1: % women aged 20-24 married before 18 (average 2005-2020)

```{r visualisation}

rate_map <- ggplot() +
 geom_sf(data = countries, fill = "grey", colour = "black") +
  geom_sf(
    mapping = aes(fill = latest_value),
    data = cmf1,
    stat = "sf",
    position = "identity",
    colour = "black",
    expand = TRUE
    ) +
  scale_fill_fermenter(
    name = NULL,
    palette = "YlOrBr",
    direction = 1,
    labels = scales::label_number(suffix = "%"),
    na.value = "grey") + 
  labs(
    title = "CHILD MARRIAGE",
    subtitle = "% women aged 20-24 married before 18 (average 2005-2020)",
    caption = paste(
      "**CHART:** Ambalika Gupta & James Goldie, 360info",
      "**DATA:** UNStats",
      sep = "<br>")) +
  #coord_sf(crs = "ESRI:54012") +
  theme_360() +
  theme(
    legend.position = "top",
    legend.direction = "horizontal",
    legend.key.width = unit(2, "cm"),
    panel.grid = element_blank()
  )

save_360plot(rate_map, "rate_map.png", retina = 4, shape = "sdtv-landscape")

```

### Final Chloropleth + Pattern Map with save option

```{r}

combined_map <- ggplot() +
  geom_sf(data = countries,
          mapping = aes(fill = NULL)) +
  geom_sf_pattern(
    mapping = aes(
      pattern_spacing = LawStr,
      pattern_density = LawStr,
      pattern_angle   = LawStr,
      pattern         = LawStr,
      fill = latest_value
    ),
    data = cmf1,
    stat = "sf",
    position = "identity",
    colour = "black",
    #pattern = 'stripe',
    pattern_aspect_ratio = 1.8,
    pattern_fill = "black",
    pattern_alpha = 0.4
  ) +
  scale_pattern_density_discrete(range = c(0.01, 0.3)) +
  scale_pattern_spacing_discrete(range = c(0.01, 0.03)) +
  scale_fill_fermenter(name = "Child Marriage Rate", palette = "YlOrBr", direction = 1) +
  labs(
    title = "CHILD MARRIAGE",
    subtitle = "Average child marriage rate (2005-2020) and legality",
    caption = paste(
      "**CHART::** Ambalika Gupta & James Goldie, 360info",
      "**DATA::** World Bank",
      sep = "<br>"
    )
  ) 
  
ggsave(
  "chart_test.png" ,
  plot = combined_map,
  scale = 0.9,
  width = 20,
  height = 10,
  units = "cm",
  dpi = 320
)

```


### Plot 2: Avg Child Marriage Rate in Sub Continental Region during Covid-19

```{r}

child_marriage <- read_csv("data/child_marriage/child_marriage.csv")

child_covid <- child_marriage %>%
  clean_names()

child_covid <- child_covid %>%
  filter(time_period_time_period == 2021) %>%
  filter(!geographic_area %in% c("Fiji", "Denmark", "Singapore"))

ggplot(data = child_covid, aes(
  y = reorder(geographic_area, obs_value_observation_value),
  x = obs_value_observation_value
)) +
  geom_bar(fill = "steelblue",
           stat = "identity") +
  geom_text(
    aes(label = obs_value_observation_value),
    hjust = 1.6,
    color = "white",
    size = 3.5
  ) +
  labs(title = "Average Child Marriage Rate in Sub Continental Region during Covid-19") +
  theme(axis.text.x = element_text(
    angle = 90,
    vjust = 0.5,
    hjust = 1
  ),
  legend.position = "none") +
  xlab("Child Marriage Rate") +
  ylab("Region") +
  theme_360()

```














