---
title: "healthecon"
author: "Ambalika"
date: "2023-04-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r package}

library(readr)
library(readxl)
library(janitor)
library(tidyverse)
library(rnaturalearth)
library(ggplot2)
library(plotly)
library(themes360info)
library(rio)

```

```{r readdata}

hdi_timeseries <- read_csv("data/healtheconomics/hdi_timeseries.csv")

hdi_timeseries <- hdi_timeseries %>% 
  pivot_longer(
    cols = 6:37,
    names_to = "year",
    values_to = "HDI"
  )

hdi_timeseries <- hdi_timeseries %>% 
  select(c(-region, -hdicode, -hdi_rank_2021)) %>% 
  mutate(year = str_remove_all(year, "hdi_")) %>% 
  mutate(year = as.numeric(year)) %>% 
  filter(year > 2014)


hdif <- read_excel("data/healtheconomics/hdi.xlsx")

hdif <- hdif %>% 
  clean_names()

whr <- read_excel("data/healtheconomics/wellbeing-otherfactos.xls")

whr <- whr %>% 
  clean_names()

whr <- whr %>% 
  mutate(score = life_ladder/10)

combined <- whr %>% 
  left_join(hdi, by = c("country_name" = "country"))

final <- combined %>% 
  select(country_name, year, score)

whr <- whr %>% 
  mutate(WHR = life_ladder/10)

final <- merge(whr, hdi_timeseries, by.x = c("country_name", "year"), by.y = c("country", "year")) %>% 
  select(country_name, year, 13:15)

final1 <- final %>% 
  pivot_longer(cols = c(3,4),
               names_to = "organisation",
               values_to = "score")

countries <- ne_countries(returnclass = "sf", scale = "medium")

geo <- countries %>% 
  select(admin, iso_a3, subregion, region_wb)

combined <- merge(final1, geo, by.x = "iso3", by.y = "iso_a3")


```


```{r}


southasia <- combined %>% 
  filter( subregion == "Southern Asia")

centralasia <- combined %>% 
  filter( subregion == "Central Asia")

westernasia <- combined %>% 
  filter( subregion == "Western Asia")

easternasia <- combined %>% 
  filter( subregion == "Eastern Asia")

seasia <- combined %>% 
  filter( subregion == "South-Eastern Asia")

ausnz <- combined %>% 
  filter( subregion == "Australia and New Zealand")

```

```{r}

ggplotly(
  southasia %>% 
    ggplot(aes(x = year, 
               y = score, 
               color = organisation)) +
    geom_line() +
    geom_point() +
    theme(legend.position = "bottom") + 
    facet_wrap( ~ country_name, 
                nrow = 4))


```


```{r}

ggplotly(
  centralasia %>% 
    ggplot(aes(x = year, 
               y = score, 
               color = organisation)) +
    geom_line() +
    geom_point() +
    theme(legend.position = "bottom") + 
    facet_wrap( ~ country_name, 
                nrow = 4))


```


```{r}

ggplotly(
  westernasia %>% 
    ggplot(aes(x = year, 
               y = score, 
               color = organisation)) +
    geom_line() +
    geom_point() +
    theme(legend.position = "bottom") + 
    facet_wrap( ~ country_name, 
                ncol = 3))

```

```{r}

ggplotly(
  easternasia %>% 
    ggplot(aes(x = year, 
               y = score, 
               color = organisation)) +
    geom_line() +
    geom_point() +
    theme(legend.position = "bottom") + 
    facet_wrap( ~ country_name, 
                nrow = 4))

```

```{r}

ggplotly(
  seasia %>% 
    ggplot(aes(x = year, 
               y = score, 
               color = organisation)) +
    geom_line() +
    geom_point() +
    theme(legend.position = "bottom") + 
    facet_wrap( ~ country_name, 
                ncol = 3))

```

```{r}

ggplotly(
  ausnz %>% 
    ggplot(aes(x = year, 
               y = score, 
               color = organisation)) +
    geom_line() +
    geom_point() +
    theme(legend.position = "bottom") + 
    facet_wrap( ~ country_name, 
                nrow = 4))

```

```{r}

le <- read_excel("data/healtheconomics/le.xlsx")

le <- le %>% 
  pivot_longer(
    cols = 4:35,
    names_to = "year",
    values_to = "life_expectancy"
  )

le <- le %>% 
  select(c(-hdicode)) %>% 
  mutate(year = str_remove_all(year, "le_")) %>% 
  mutate(year = as.numeric(year)) %>% 
  filter(year > 2014)


```


```{r}

lifeexpectancy <- merge(final, le, by.x = c("iso3", "year"), by.y = c("iso3", "year")) %>% 
  filter(year == 2021)

geo1 <- countries %>% 
  select(admin, iso_a3, subregion, region_wb)

life_expectancy2 <- merge(lifeexpectancy, geo1, by.x = "iso3", by.y = "iso_a3")

```


```{r}

life_expectancy2 <- life_expectancy2 %>% 
  filter(subregion %in% c("Southern Asia", "Central Asia", "Western Asia", "Eastern Asia",
                          "South-Eastern Asia", "Australia and New Zealand"))

ggplotly(
  ggplot(life_expectancy2, aes(x=HDI, 
                          y=WHR, 
                          size=life_expectancy, 
                          color=subregion, 
                          text = country_name)) +
    geom_point(alpha=0.5) +
    scale_size(range = c(.1, 12), name="Subregion") +
    ylab("WHR") +
    xlab("HDI") +
    labs(title  = "Wellbeing") +
    scale_y_continuous(labels = scales::label_percent(scale = 1)) +
    scale_x_continuous(labels = scales::label_percent(scale = 1))
  )




```


```{r}

ggplotly(
  combined %>% 
    filter(country_name == 
             'India') %>% 
    ggplot(aes(x = year, 
               y = score, 
               color = organisation)) +
    geom_line() +
    geom_point() +
    theme(legend.position = "bottom")
)


```


```{r}

ggplotly(
  combined %>% 
    filter(country_name == 
             'Pakistan') %>% 
    ggplot(aes(x = year, 
               y = score, 
               color = organisation)) +
    geom_line() +
    geom_point() +
    theme(legend.position = "bottom")
)

```

```{r}

ggplotly(
  combined %>% 
    filter(country_name == 
             'Indonesia') %>% 
    ggplot(aes(x = year, 
               y = score, 
               color = organisation)) +
    geom_line() +
    geom_point() +
    theme(legend.position = "bottom")
)


```



```{r}

data <- import_list("data/healtheconomics/2015_a.xlsx" , rbind=TRUE)

factors <- data %>% 
  pivot_longer(
    cols = 2:7,
    names_to = "factors",
    values_to = "value"
  )

factors <- factors %>% 
  select(-`_file`)

factor <- merge(factors, geo, by.x = "country", by.y = "admin")

whr <- whr %>% 
  select(country_name, year, WHR)

happiness <- inner_join(whr, data, by = join_by("country_name" == "country", "year" == "year"))

happiness <- happiness %>% 
   pivot_longer(
    cols = 3:9,
    names_to = "factor",
    values_to = "value"
  )

```

```{r}


gnipc <- read_excel("data/healtheconomics/gnipic.xlsx")

gnipc <- gnipc %>% 
  pivot_longer(
    cols = 5:36,
    names_to = "year",
    values_to = "GNIPC"
  )

gnipc <- gnipc %>% 
  select(c(-hdicode)) %>% 
  mutate(year = str_remove_all(year, "gnipc_")) %>% 
  mutate(year = as.numeric(year)) %>% 
  filter(year > 2014)

hdifactor <- inner_join(le, gnipc, by = c("year", "country", "iso3"))

```


```{r}

eys <- read_excel("data/healtheconomics/eys.xlsx")

eys <- eys %>% 
  pivot_longer(
    cols = 5:36,
    names_to = "year",
    values_to = "eys"
  )

eys <- eys %>% 
  mutate(year = str_remove_all(year, "eys_")) %>% 
  mutate(year = as.numeric(year)) %>% 
  select(c(-hdicode)) %>% 
  filter(year > 2014)

hdifactor <- inner_join(hdifactor, eys, by = c("year", "country", "iso3", "region"))

```

```{r}

mys <- read_excel("data/healtheconomics/mys.xlsx")

mys <- mys %>% 
  pivot_longer(
    cols = 5:36,
    names_to = "year",
    values_to = "mys"
  )

mys <- mys %>% 
  mutate(year = str_remove_all(year, "mys_")) %>% 
  mutate(year = as.numeric(year)) %>% 
  select(c(-hdicode)) %>% 
  filter(year > 2014)

hdifactor <- inner_join(hdifactor, mys, by = c("year", "country", "iso3", "region"))

hdifactor <- inner_join(hdifactor, hdi_timeseries, by = c("year", "country", "iso3"))

hdifactor <- hdifactor %>% 
  mutate(logGNI = log(GNIPC)) %>% 
  mutate(lifeexp = life_expectancy/10) %>% 
  select(-region, -GNIPC, -life_expectancy)

hdifactor <- hdifactor %>% 
  pivot_longer(
    cols = 4:8,
    names_to = "factor",
    values_to = "value"
  )

```

```{r}

a <- ggplotly(
  hdifactor %>% 
    filter(country == 
             'Indonesia') %>% 
    ggplot(aes(x = year, 
               y = value, 
               color = factor)) +
    geom_line() +
    geom_point() +
    theme_bw() +
    scale_color_brewer(palette = "Dark2")
)

b <- ggplotly(
  happiness %>% 
    filter(country_name == 
             'Indonesia') %>% 
    ggplot(aes(x = year, 
               y = value, 
               color = factor)) +
    geom_line() +
    geom_point() +
    theme_bw() +
    scale_color_brewer(palette = "Dark2")
)

subplot(a,b)

```

```{r}

whrfactor <- import_list("data/healtheconomics/2015_a.xlsx" , rbind=TRUE)

whrfactor <- whrfactor %>% 
  select(-`_file`)

whrfactor <- whrfactor %>% 
  pivot_longer(
    cols = 2:9,
    names_to = "factor",
    values_to = "value"
  )

whrfac <- whrfactor %>% 
  filter(factor != c("residual","score"))

indonesiawhr <- whrfac %>% 
  filter(country == "India")

indonesiascore <- whrfactor %>% 
  filter(factor == "score", country == "India")

ggplotly(
  ggplot(indonesiawhr, aes(fill=factor, x=year, y=value)) + 
  scale_fill_brewer(palette = "Dark2") +
  geom_bar(position="stack", stat="identity") +
  theme_bw() +
  theme(legend.position = "top") + 
    geom_line(data = indonesiascore, aes(x = year, y = value)) +
    geom_point(data = indonesiascore)
)


```








