---
title: "WellBeing Economics"
author: "Ambalika"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

```{r package}

library(readr)
library(readxl)
library(janitor)
library(tidyverse)
library(rnaturalearth)
library(ggplot2)
library(plotly)
library(themes360info)
library(rio)

```

```{r read data}

# Reading HDI data

hdi <- read_csv("data/healtheconomics/hdi_timeseries.csv")

hdi <- hdi %>%
  pivot_longer(cols = 6:37,
               names_to = "year",
               values_to = "HDI")

hdi <- hdi %>%
  select(c(-region,-hdicode,-hdi_rank_2021)) %>%
  mutate(year = str_remove_all(year, "hdi_")) %>%
  mutate(year = as.numeric(year))

# Reading WHR(World Happiness Record) data

whr <- read_excel("data/healtheconomics/wellbeing-otherfactos.xls")

whr <- whr %>%
  clean_names() %>%
  mutate(WHR = life_ladder / 10)

# Comparison data

comparison <- whr %>%
  left_join(hdi, by = c("country_name" = "country", "year")) %>%
  select(country_name, year, 13:15)

comparison <- comparison %>%
  pivot_longer(cols = c(3, 5),
               names_to = "organisation",
               values_to = "score")

comparison$organisation[comparison$organisation == "WHR"] <-
  "Life Ladder Score"
comparison$organisation[comparison$organisation == "HDI"] <-
  "Human Development Index"

filtered <- comparison %>% 
  filter(country_name %in% c("Australia", "Afghanistan", "India", "Indonesia", "Malaysia", "Pakistan"))

```

```{r}

ggplot(data = filtered,
       aes(x = year,
           y = score,
           color = organisation)) +
  geom_line(size = 1) +
  geom_point(size = 2) +
  scale_y_continuous(labels = scales::label_percent()) +
  scale_color_manual(values=c("#d73027", "#4575b4")) +
  labs(
    title = "Measuring Wellbeing",
    subtitle = paste("The Human Development Index is a gold standard for measuring a country’s progress." ,
                     "The Life Ladder score, measured by the annual World Happiness Report, asks survey respondents to rate their lives.", "It often tells a very different story.", 
                     sep = "\n"),
    y = "Score",
    caption = paste(
      "**CHART:** Ambalika Gupta & James Goldie, 360info",
      "**DATA:** UNDP & World Happiness Report",
      sep = "\n"
    )
  ) +
  facet_wrap(~ country_name,
               ncol = 2) +
  theme_360() +
  theme(
    legend.position = "top",
    legend.direction = "horizontal",
    axis.title.x = element_blank(),
    legend.title = element_blank(),
    legend.key.width = unit(1, "cm") ,
    panel.grid = element_blank(),
    plot.title=element_text(face="bold"),
    strip.text = element_text(face="bold"), 
    plot.subtitle=element_text(size=12, color="black")
  )

```


```{r india}

# India

india <- comparison %>%
  filter(country_name == "India")

ggplot(data = india,
       aes(x = year,
           y = score,
           color = organisation)) +
  geom_line(size = 1) +
  geom_point(size = 2) +
  scale_color_manual(values=c("#377EB7", "#EF3E30")) +
  labs(
    title = "Wellbeing Economics: India",
    subtitle = "Comparing Human Development Index with World Happiness Score",
    color = "Organisation",
    x = "Year",
    y = "Score",
    caption = paste(
      "**CHART:** Ambalika Gupta & James Goldie, 360info",
      "**DATA:** UNDP & World Happiness Report",
      sep = "\n"
    )
  ) +
  theme_360() +
  theme(
    legend.position = "top",
    legend.direction = "horizontal",
    legend.key.width = unit(1, "cm") 
  )

```

```{r paki}

# Pakistan

pakistan <- comparison %>%
  filter(country_name == "Pakistan")

ggplot(data = pakistan,
       aes(x = year,
           y = score,
           color = organisation)) +
  geom_line(size = 1) +
  geom_point(size = 2) +
  labs(
    title = "Wellbeing Economics: Pakistan",
    subtitle = "Comparing Human Development Index with World Happiness Score",
    color = "Organisation",
    x = "Year",
    y = "Score",
    caption = paste(
      "**CHART:** Ambalika Gupta & James Goldie, 360info",
      "**DATA:** UNDP & World Happiness Report",
      sep = "\n"
    )
  ) +
  theme_360() +
  annotate_360_light(
    x = 2017,
    y = 0.52,
    label = paste(
      "Happiness score is more than ", 
      "Human Development Index for 2019", 
      sep = "<br>"
    ),
    size = 2
  ) +
  theme(
    legend.position = "top",
    legend.direction = "horizontal",
    legend.key.width = unit(1, "cm") 
  )

```

```{r indonesia}

# Indonesia

indonesia <- comparison %>%
  filter(country_name == "Indonesia")

ggplot(data = indonesia,
       aes(x = year,
           y = score,
           color = organisation)) +
  geom_line(size = 1) +
  geom_point(size = 2) +
  labs(
    title = "Wellbeing Economics: Indonesia",
    subtitle = "Comparing Human Development Index with World Happiness Score",
    color = "Organisation",
    x = "Year",
    y = "Score",
    caption = paste(
      "**CHART:** Ambalika Gupta & James Goldie, 360info",
      "**DATA:** UNDP & World Happiness Report",
      sep = "\n"
    )
  ) +
  theme_360() +
  theme(
    legend.position = "top",
    legend.direction = "horizontal",
    legend.key.width = unit(1, "cm") 
  )

```

```{r thai}

# Thailand

thailand <- comparison %>%
  filter(country_name == "Thailand")

ggplot(data = thailand,
       aes(x = year,
           y = score,
           color = organisation)) +
  geom_line(size = 1) +
  geom_point(size = 2) +
  labs(
    title = "Wellbeing Economics: Thailand",
    subtitle = "Comparing Human Development Index with World Happiness Score",
    color = "Organisation",
    x = "Year",
    y = "Score",
    caption = paste(
      "**CHART:** Ambalika Gupta & James Goldie, 360info",
      "**DATA:** UNDP & World Happiness Report",
      sep = "\n"
    )
  ) +
  theme_360() +
  theme(
    legend.position = "top",
    legend.direction = "horizontal",
    legend.key.width = unit(1, "cm") 
  )

```

```{r sgp}

# Singapore

singapore <- comparison %>%
  filter(country_name == "Singapore")

ggplot(data = singapore,
       aes(x = year,
           y = score,
           color = organisation)) +
  geom_line(size = 1) +
  geom_point(size = 2) +
  labs(
    title = "Wellbeing Economics: Singapore",
    subtitle = "Comparing Human Development Index with World Happiness Score",
    color = "Organisation",
    x = "Year",
    y = "Score",
    caption = paste(
      "**CHART:** Ambalika Gupta & James Goldie, 360info",
      "**DATA:** UNDP & World Happiness Report",
      sep = "\n"
    )
  ) +
  theme_360() +
  theme(
    legend.position = "top",
    legend.direction = "horizontal",
    legend.key.width = unit(1, "cm") 
  )

```

```{r myanmar}

# Myanmar

myanmar <- comparison %>%
  filter(country_name == "Myanmar")

ggplot(data = myanmar,
       aes(x = year,
           y = score,
           color = organisation)) +
  geom_line(size = 1) +
  geom_point(size = 2) +
  labs(
    title = "Wellbeing Economics: Myanmar",
    subtitle = "Comparing Human Development Index with World Happiness Score",
    color = "Organisation",
    x = "Year",
    y = "Score",
    caption = paste(
      "**CHART:** Ambalika Gupta & James Goldie, 360info",
      "**DATA:** UNDP & World Happiness Report",
      sep = "\n"
    )
  ) +
  theme_360() +
  theme(
    legend.position = "top",
    legend.direction = "horizontal",
    legend.key.width = unit(1, "cm") 
  )
```

```{r aus}

# Australia

aus <- comparison %>%
  filter(country_name == "Australia")

ggplot(data = aus,
       aes(x = year,
           y = score,
           color = organisation)) +
  geom_line(size = 1) +
  geom_point(size = 2) +
  labs(
    title = "Wellbeing Economics: Australia",
    subtitle = "Comparing Human Development Index with World Happiness Score",
    color = "Organisation",
    x = "Year",
    y = "Score",
    caption = paste(
      "**CHART:** Ambalika Gupta & James Goldie, 360info",
      "**DATA:** UNDP & World Happiness Report",
      sep = "\n"
    )
  ) +
  theme_360() +
  theme(
    legend.position = "top",
    legend.direction = "horizontal",
    legend.key.width = unit(1, "cm")
    ) 

```


```{r nz}

# New Zealand

nz <- comparison %>%
  filter(country_name == "New Zealand")

ggplot(data = nz,
       aes(x = year,
           y = score,
           color = organisation)) +
  geom_line(size = 1) +
  geom_point(size = 2) +
  labs(
    title = "Wellbeing Economics: New Zealand",
    subtitle = "Comparing Human Development Index with World Happiness Score",
    color = "Organisation",
    x = "Year",
    y = "Score",
    caption = paste(
      "**CHART:** Ambalika Gupta & James Goldie, 360info",
      "**DATA:** UNDP & World Happiness Report",
      sep = "\n"
    )
  ) +
  theme_360() +
  theme(
    legend.position = "top",
    legend.direction = "horizontal",
    legend.key.width = unit(1, "cm")
  )

```







































