---
title: "ETC5543_Report"
author: "Ambalika"
date: "2023-05-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Topic: Health Economics

HDI vs WHR - Human Development Index v/s World Happiness Report Score

Human Development Index aims to measure the quality of life in following terms: Health, Knowledge and Standard of living(based on income). It takes into account the following factors: Life expectancy at birth (years), Expected years of schooling (years), Mean years of schooling (years), GNI per capita (2017 PPP$).

World Happiness Report is based on the overall life satisfaction of an individual. It depends on various factors like  GDP per capita, social support, healthy
life expectancy, freedom to make life choices, generosity, and freedom from corruption


Is it right to compare a factor which measures life satisfaction of an individual in terms of happiness, wealth, health, social life, freedom and point of view.Is it subjective?
 It is about comparing goenment efforts vs human acceptance. It is abiyt turning aorround thi stigma bcoz od fwnder he has to care for you. zone ouisde can je work on her choices. 

avwrage hdi is measured as an average of all indices taken into account and ciiined it is not inclined twsrds shen hal',, we ndivide by 10 tyo make in ocmpaaiable to HDDO . It is not the right siw ro measysa a system; 


child marriage - rate of child marriage vs the law regarding child marriage. 

We ibserve high child marriage rates in Asia and Africa, Africa owuls still be ruled by monarhc. They need to revise child marriage laws and make them more stringent. Owing to this during COvid we observed stricter laws on child marriage. Girls need more to be educated and to lead a healthy lifestyle. 

MEthodology used:
QGIS
ggpattern
renv lock



































